# -*- coding: utf-8 -*-
"""research_extract  questions using img file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VX-NG7urcZAwKR4HbYMPlGUG0D_WYUPN
"""

# Install Tesseract OCR
!sudo apt install tesseract-ocr
!pip install pytesseract Pillow

from google.colab import files

uploaded = files.upload()  # Upload your .jpg or .png file

from PIL import Image
import pytesseract

# Load image (replace with your file name if different)
image = Image.open('2016 - 1.jpeg')  # Example image you uploaded

# Extract text
text = pytesseract.image_to_string(image)

# Show the text
print(text)

# Save the text to a file
with open("output_2016.txt", "w", encoding="utf-8") as f:
    f.write(text)

# Download the file
files.download("output_2016.txt")

"""multiple images

"""

# Step 1: Install Tesseract OCR
!sudo apt install tesseract-ocr
!pip install pytesseract Pillow

# Step 2: Upload multiple images
from google.colab import files
uploaded = files.upload()  # Select multiple image files here

import pytesseract
from PIL import Image

all_text = ""  # Store all extracted text

# Step 3: Loop through uploaded images
for filename in uploaded.keys():
    print(f"Processing {filename}...")
    image = Image.open(filename)
    text = pytesseract.image_to_string(image)
    all_text += f"\n--- {filename} ---\n" + text  # Add filename for reference

# Step 4: Show all extracted text
print(all_text)

# Step 5: Save combined text to a file
with open("combined_output.txt", "w", encoding="utf-8") as f:
    f.write(all_text)

# Step 6: Download the file
files.download("combined_output.txt")

"""saving data into excel"""

import pandas as pd

# Example dataset
data = [
    ["2016", 1, "MCQ", "What is the main function of an operating system?", "Operating Systems", ""],
    ["2018", 14, "Structured", "Refer to the diagram and answer the questions.", "Networking", "q2018_14.jpg"]
]

# Create DataFrame
df = pd.DataFrame(data, columns=["Year", "Question No.", "Question Type", "Question Text", "Topic", "Image File"])

# Save to CSV
df.to_csv("ICT_Past_Papers_Dataset.csv", index=False)

# Download file
from google.colab import files
files.download("ICT_Past_Papers_Dataset.csv")